services: &services
  _defaults: &defaults
    autowire: true
    autoconfigure: true
  
  FRZB\Component\RequestMapper\:
    resource: '../../{EventListener,ExceptionFormatter,ExceptionMapper,Extractor,RequestMapper,PropertyMapper,ClassMapper}/**'
    exclude: '../../{Helper,ValueObject,Attribute,Request,Data,Exception,Tests}/**'

when@test:
  services:
    <<: *services
    _defaults:
      <<: *defaults
      public: true
