build:
  nodes:
    analysis:
      tests:
        override:
        - php-scrutinizer-run
  
  environment:
    php: 8.1.9

filter:
  excluded_paths:
  - "Resources/*"
  - "Tests/*"
  - "var/*"
  - "build/*"
  dependency_paths:
  - "vendor/*"
