build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
    coverage:
      tests:
        override:
          - command: composer test

  environment:
    php: 8.1.9

filter:
  excluded_paths:
    - "Tests/*"
    - "var/*"
    - "Resources/*"
  dependency_paths:
    - "vendor/*"
