build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
    coverage:
      tests:
        override:
          - command: mkdir -p var/tests/coverage && php -n -dzend_extension=xdebug -dxdebug.mode=coverage vendor/bin/phpunit --colors=always --configuration phpunit.xml.dist --log-junit var/tests/.phpunit.output.xml --coverage-clover var/tests/coverage/coverage.xml
            coverage:
              file: var/tests/coverage/coverage.xml
              format: clover
  environment:
    php: 8.1

filter:
  excluded_paths:
    - "Tests/*"
    - "var/*"
    - "Resources/*"
  dependency_paths:
    - "vendor/*"
