language: php
dist: impish

matrix:
  include:
    - php: 8.1

install:
  - travis_retry composer install

script:
  - mkdir -p build/logs
  - php -n -dzend_extension=xdebug -dxdebug.mode=coverage vendor/bin/phpunit --colors=always --configuration phpunit.xml.dist --log-junit build/logs/.phpunit.output.xml --coverage-clover build/logs/clover.xml

after_success:
  - vendor/bin/php-coveralls -v
  - bash <(curl -s https://codecov.io/bash) -t 7f81cbf0-1181-488f-a659-3868a104acac
