language: php
dist: impish
sudo: false

matrix:
  include:
    - php: 8.0

install:
  - travis_retry composer install --no-suggest --prefer-dist -n -o

script:
  - mkdir -p build/logs
  - php -n -dzend_extension=xdebug -dxdebug.mode=coverage vendor/bin/phpunit --colors=always --verbose --configuration phpunit.xml.dist --log-junit build/logs/.phpunit.output.xml --coverage-clover build/logs/clover.xml

after_success:
  - vendor/bin/php-coveralls -v
  - bash <(curl -s https://codecov.io/bash) -t 7f81cbf0-1181-488f-a659-3868a104acac
